version: "3.9"
services:
#  database:
#    image: mysql:5.7
#    volumes:
#      - db_data:/var/lib/mysql
#    ports:
#      - "3306:3306"
  web:
    image: timg:latest
    ports:
      - "80:8080"
volumes:
  db_data: {}